Improved path handling for imports (WIP)
urbas/rix pull request #127
Opened 2024-05-09 21:58 UTC by arduano

Improved path handling for imports (WIP)

Slightly improved path handling for the import builtin, non-absolute string handling will be fixed in the future.

2024-05-14 17:32 UTC, urbas commented on nixjs-rt/src/builtins.ts
> +        // TODO: Get relative paths working
Relative paths aren't supported in import when using strings. Here's an example:
```bash
% nix eval --impure --expr 'let flake = builtins.import "./flake.nix"; in flake.description'            
error:
       … while calling the 'import' builtin

         at «string»:1:13:

            1| let flake = builtins.import "./flake.nix"; in flake.description
             |             ^

       … while realising the context of a path

         at «none»:0: (source not available)

       error: string './flake.nix' doesn't represent an absolute path
```

2024-05-15 10:25 UTC, urbas requested changes
Looks great, but I think importing relative paths as strings is not supported by nix, so can you please replace that part of the logic with an error (instead of that TODO)?

2024-05-15 10:32 UTC, arduano commented
Hey yeah sorry for not getting the chance to address these, only got time to address 1 PR on the train before I went afk for a few days, will address in a day or two

2024-05-15 10:33 UTC, arduano commented
By the way does reviewing these feel easier or harder? Than just conventional large PRs

2024-05-15 13:40 UTC, urbas commented
> By the way does reviewing these feel easier or harder? Than just conventional large PRs

I'm using plain github to review and it's pretty easy. Thanks for breaking these up! 👍

2024-05-26 08:09 UTC, urbas commented on nixjs-rt/src/builtins.ts
> +      }
Nitpick: you move the type exception from line 358 to here and remove the `if` block above:
```suggestion
      } else {
        const expected = [Path, NixString];
        throw builtinBasicTypeMismatchError("import", pathStrict, expected);
      }
```

2024-05-26 08:11 UTC, urbas commented on nixjs-rt/src/builtins.ts
> +          "builtins-import-non-absolute-path",
Nitpick: Maybe add a test for this? Feel free to ignore or add in a separate PR.

2024-05-26 08:12 UTC, urbas approved these changes

2024-05-26 08:12 UTC, merged